boss_bar: true                             # Boss bar when looking at furniture
prevent_furniture_break_with_tools: true
prevent_furniture_break_with_sword: true
double_hit_destroy_mechanic: true          # Destroy furniture with double hit
count_shears_as_silktouch: [ ]             # List of STRINGBLOCKs ids